### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by GuanhuaWang** [kuangliu/pytorch-cifar#66]
ubuntu@ip-172-31-35-111:~/pytorch-cifar$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from models import *
  File "/home/ubuntu/pytorch-cifar/models/__init__.py", line 1, in <module>
    from vgg import *
ModuleNotFoundError: No module named 'vgg'

**Comment by qianjinhao** [comment]
I have the same problems

**Comment by yanjj16** [comment]
even if you changed "from vgg import *" into "from .vgg import *",there also have some other problems like this:
"Traceback (most recent call last):
  File "D:/pytorch-cifar-master/pytorch-cifar-master/main.py", line 16, in <module>
    from .models import *
ImportError: attempted relative import with no known parent package"
is anyone can help me?

**Comment by safaasawalhah** [comment]
even if i changed "from vgg import *" into "from .vgg import *",there also have some other problems like this:
'self.cnn=vgg.vgg11 ()'
NameError:name 'vgg' is not defined.
is anyone can help me?
Knowing that I am trying to change the code from Python 2 to Python 3 using Anaconda
